<a href="https://colab.research.google.com/github/Sunitha-k2006/sunitha-codeboosters-internship-2026/blob/main/Phase_01_Data_Engineering/Day_04_BigData_PySpark_Architecture/Copy_of_Day_04_Machine_Learning_and_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
a=pd.read_csv("/content/SOCR-HeightWeight.csv")

In [ ]:
a.head()

   Index  Height(Inches)  Weight(Pounds)
0      1        65.78331        112.9925
1      2        71.51521        136.4873
2      3        69.39874        153.0269
3      4        68.21660        142.3354
4      5        67.78781        144.2971

In [ ]:
x=a[['Height(Inches)']]
y=a[['Weight(Pounds)']]

In [ ]:
a.isnull().any()
a.isnull().sum()

Index             0
Height(Inches)    0
Weight(Pounds)    0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
#splits the data for training and testing - 4 components
#test_size -> the percentage of data to be used for testing

In [ ]:
x_train

       Height(Inches)
9259         70.55747
1442         70.04554
5654         71.27290
9187         67.47051
18572        65.94714
...               ...
20450        68.19770
13072        67.29233
24060        71.95831
23981        66.12776
9542         68.09860

[20000 rows x 1 columns]

In [ ]:
#select and import model----
from sklearn.linear_model import LinearRegression
model=LinearRegression()

#to train the model
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
#to test the data - the output in the model predicted value
model.predict(x_test)

array([[135.73631407],
       [124.15722521],
       [133.15417259],
       ...,
       [114.03541602],
       [125.57086654],
       [126.80949092]])

In [ ]:
y_pred=model.predict(x_test)

In [ ]:
# we use this to minus the prdeicted answer with y test
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [ ]:
mean_absolute_error(y_test,y_pred)

8.05958066569989

In [ ]:
mean_squared_error(y_test,y_pred)

101.93216170118505

In [ ]:
r2_score(y_test,y_pred)

0.2459172194533752

In [ ]:
import joblib

In [ ]:
joblib.dump(model,"linear.pkl")

['linear.pkl']

In [ ]:
!pip install pyspark --quiet
print("PySpark installation complete!")

PySpark installation complete!

In [ ]:
from pyspark.sql import SparkSession

from pyspark.sql import functions as F

from pyspark.sql.functions import year, month, to_date, col, round as spark_round

import matplotlib.pyplot as plt
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

spark=SparkSession.builder \
  .appName('Day4_BigData_Sales') \
  .config('Spark.sql.adaptive.enabled', 'true') \
  .getOrCreate()

print(f"Spark version : {spark.version}")
print(f"SparkSession : ACTIVE")
print(f"Application : {spark.sparkContext.appName}")

Spark version : 4.0.2
SparkSession : ACTIVE
Application : Day4_BigData_Sales

# BIG DATA AND PySPARK

In [ ]:
df_bronze =spark.read \
   .option('header','true') \
   .option('inferSchema','true') \
   .csv("large_sales_data.csv")

print("=== BRONZE LAYER -Raw Data ===")
print(f'Rows : {df_bronze.count()}')

print(f'Columns : {len(df_bronze.columns)}')
print(f"Names : {df_bronze.columns}")
print()
df_bronze.printSchema()

=== BRONZE LAYER -Raw Data ===
Rows : 5000
Columns : 13
Names : ['order_id', 'customer_name', 'product', 'category', 'quantity', 'unit_price', 'revenue', 'order_date', 'city', 'region', 'sales_rep', 'payment_method', 'order_status']

root
 |-- order_id: integer (nullable = true)
 |-- customer_name: string (nullable = true)
 |-- product: string (nullable = true)
 |-- category: string (nullable = true)
 |-- quantity: integer (nullable = true)
 |-- unit_price: integer (nullable = true)
 |-- revenue: integer (nullable = true)
 |-- order_date: date (nullable = true)
 |-- city: string (nullable = true)
 |-- region: string (nullable = true)
 |-- sales_rep: string (nullable = true)
 |-- payment_method: string (nullable = true)
 |-- order_status: string (nullable = true)

In [ ]:
print("First 5 rows")
df_bronze.show(5,truncate=False)

print('\nBasic statistics for numerical columns')
df_bronze.select('quantity','unit_price','revenue').describe().show()

First 5 rows
+--------+-------------+----------+-----------+--------+----------+-------+----------+---------+------+-----------+----------------+------------+
|order_id|customer_name|product   |category   |quantity|unit_price|revenue|order_date|city     |region|sales_rep  |payment_method  |order_status|
+--------+-------------+----------+-----------+--------+----------+-------+----------+---------+------+-----------+----------------+------------+
|1001    |Sneha Reddy  |Monitor   |Electronics|12      |22000     |264000 |2023-05-21|Mumbai   |West  |Meera Patel|UPI             |Delivered   |
|1002    |Ramesh Kumar |Printer   |Electronics|10      |12000     |120000 |2023-08-05|Delhi    |North |Anil Sharma|Credit Card     |Shipped     |
|1003    |Rahul Mishra |Mouse     |Accessories|10      |800       |8000   |2023-01-14|Ahmedabad|West  |Meera Patel|Cash on Delivery|Shipped     |
|1004    |Suresh Rao   |Tablet    |Electronics|5       |32000     |160000 |2023-01-04|Surat    |West  |Ravi Kumar |Cash on Delivery|Processing  |
|1005    |Priya Patel  |Headphones|Electronics|4       |3500      |14000  |2023-06-22|Bangalore|South |Sunita Rao |Cash on Delivery|Delivered   |
+--------+-------------+----------+-----------+--------+----------+-------+----------+---------+------+-----------+----------------+------------+
only showing top 5 rows

Basic statistics for numerical columns
+-------+-----------------+------------------+------------------+
|summary|         quantity|        unit_price|           revenue|
+-------+-----------------+------------------+------------------+
|  count|             5000|              5000|              5000|
|   mean|           7.9536|          12496.86|          99169.52|
| stddev|4.275313169878912|14857.384309295603|145972.97195261103|
|    min|                1|               600|               600|
|    max|               15|             45000|            675000|
+-------+-----------------+------------------+------------------+

In [ ]:
df_bronze.write \
  .mode('overwrite') \
  .parquet('sales_bronze.parquet')

print('Bronze Parquet saved: sales_bronze.parquet')
import os

Bronze Parquet saved: sales_bronze.parquet

In [ ]:
import pandas as pd
b=pd.read_csv("/content/data.csv")

In [ ]:
b.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [ ]:
X = b[['bedrooms', 'bathrooms', 'sqft_living', 'floors']]
Y = b[['price']]

In [ ]:
b.isnull().any()

date             False
price            False
bedrooms         False
bathrooms        False
sqft_living      False
sqft_lot         False
floors           False
waterfront       False
view             False
condition        False
sqft_above       False
sqft_basement    False
yr_built         False
yr_renovated     False
street           False
city             False
statezip         False
country          False
dtype: bool

In [ ]:
b.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)

In [ ]:
x_train

      bedrooms  bathrooms  sqft_living  floors
950        3.0       2.25         1990     2.0
4109       2.0       2.00         1170     1.5
2302       3.0       1.75         1520     1.0
1364       4.0       2.25         1940     1.0
495        5.0       3.00         4530     1.5
...        ...        ...          ...     ...
1586       4.0       2.75         3310     2.0
1479       7.0       4.50         4140     1.0
3874       3.0       2.50         1840     1.0
2172       3.0       3.50         1500     2.0
3389       4.0       3.50         4660     2.0

[3680 rows x 4 columns]

In [ ]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
model.predict(x_test)

array([[ 596919.5036551 ],
       [ 365462.40890321],
       [ 454455.84975199],
       [ 391354.48086083],
       [ 701053.86462519],
       [ 875996.44099961],
       [ 404301.31108167],
       [ 630019.974611  ],
       [ 398135.18361072],
       [ 757226.58062875],
       [ 273879.00427923],
       [ 238080.21889901],
       [ 581637.21431434],
       [ 521970.63989948],
       [1021926.31946527],
       [ 185026.93264991],
       [ 437537.37424805],
       [ 359044.56145773],
       [ 679327.29018687],
       [ 540630.65988749],
       [ 509529.23039917],
       [ 486198.29217133],
       [ 808791.63085238],
       [ 615609.75753269],
       [ 650393.90523434],
       [ 422281.52255937],
       [ 467680.83759944],
       [1126823.5981394 ],
       [ 524532.96982593],
       [ 390649.82318251],
       [ 623038.44641925],
       [ 305258.59139416],
       [ 419835.32039697],
       [ 879599.84625671],
       [ 567593.93530815],
       [1563930.02107597],
       [ 434301.81672954],
       [ 380207.45514979],
       [ 712311.63337871],
       [ 561793.55357955],
       [ 797981.02279367],
       [ 513132.63565628],
       [ 492785.14268502],
       [1813536.33037376],
       [ 448821.58065365],
       [ 418651.67965019],
       [ 443534.4986508 ],
       [ 209151.82638065],
       [ 751014.55105929],
       [ 706682.74900195],
       [ 967520.38940119],
       [ 289976.3020534 ],
       [ 420650.72111777],
       [ 582820.85506112],
       [ 430867.41454064],
       [ 495062.34177921],
       [ 468101.56064218],
       [ 506320.11053273],
       [ 705414.80286476],
       [ 978616.12829215],
       [ 348880.35105162],
       [ 273879.00427923],
       [ 456449.506498  ],
       [ 859782.2308866 ],
       [ 612538.2106482 ],
       [ 274667.96734795],
       [ 224008.0079571 ],
       [ 780899.3212305 ],
       [ 436721.97352725],
       [ 320935.16612559],
       [ 431656.37760936],
       [ 520903.12691675],
       [ 653997.31049144],
       [ 670883.96362172],
       [ 473084.04736635],
       [ 810253.42922577],
       [ 523969.68136706],
       [ 932258.84711515],
       [ 732659.12634997],
       [ 481527.37393149],
       [ 496046.74556821],
       [ 310293.56113509],
       [ 507225.5936529 ],
       [ 297352.5079232 ],
       [ 410181.91543297],
       [1215275.6073691 ],
       [ 532160.89567027],
       [ 446801.48625557],
       [ 466470.75920059],
       [ 476939.56488538],
       [ 268250.11990247],
       [ 328142.36892719],
       [ 679327.29018687],
       [1048387.45689072],
       [ 535227.45012058],
       [ 473873.01043507],
       [ 577560.21071034],
       [ 477923.96867439],
       [ 653208.34742272],
       [ 401849.33191031],
       [ 419609.64578712],
       [ 657711.45879103],
       [ 431119.52680257],
       [ 552677.39170973],
       [ 491827.17654809],
       [ 243709.10327577],
       [ 672909.44274138],
       [ 654812.71121224],
       [ 494246.94105841],
       [ 400949.6257991 ],
       [ 871750.43432741],
       [ 738430.57614286],
       [ 477418.54795385],
       [1469001.90437507],
       [ 615042.28054893],
       [ 606151.79328897],
       [ 882245.28537689],
       [ 542655.74671975],
       [ 684140.77384283],
       [ 343845.38131069],
       [ 508882.83274658],
       [ 801952.66807676],
       [ 673698.40581011],
       [ 615267.95515878],
       [ 403764.06798749],
       [ 368134.28567546],
       [ 459237.5110343 ],
       [1473447.14800505],
       [ 711943.39335273],
       [ 365714.52116514],
       [ 320940.55084716],
       [ 925867.04503435],
       [ 602521.95037979],
       [ 430472.73686258],
       [ 359101.23299938],
       [ 469758.79973586],
       [ 984523.17029553],
       [ 445223.56011812],
       [ 306073.99211496],
       [ 642739.54173792],
       [ 553408.48704013],
       [ 733138.10941844],
       [ 667506.63299567],
       [ 482652.75465255],
       [ 554560.30541326],
       [ 238080.21889901],
       [ 302023.42616304],
       [ 552534.82629361],
       [ 386625.30259527],
       [ 319699.04236205],
       [ 625852.88860763],
       [ 537647.2146309 ],
       [ 374972.85616369],
       [ 637110.65736116],
       [ 611780.67766573],
       [ 607192.86861962],
       [ 328142.36892719],
       [ 340132.42920779],
       [ 386877.4148572 ],
       [ 256992.35114895],
       [ 234476.8136419 ],
       [ 673698.40581011],
       [ 433009.02142435],
       [ 425464.20477373],
       [ 433965.3990772 ],
       [ 385836.33952655],
       [ 403795.89036113],
       [ 342214.57986909],
       [ 842564.93711295],
       [ 533649.13169574],
       [ 347448.7865678 ],
       [ 366360.91881774],
       [ 563876.90043753],
       [ 252604.9752573 ],
       [ 724016.56282705],
       [ 237291.25583028],
       [ 496022.40217858],
       [ 533228.408653  ],
       [ 685181.84917348],
       [ 418257.00197213],
       [ 690947.9142448 ],
       [ 418230.56432006],
       [ 206332.39175809],
       [ 658778.57561946],
       [ 592421.38472097],
       [ 630608.11223787],
       [ 851008.26367809],
       [ 752784.2313036 ],
       [ 497935.04399331],
       [1492648.99189953],
       [1001830.93875594],
       [ 817234.95741752],
       [ 656811.75267982],
       [ 665702.23993978],
       [ 510460.75888402],
       [ 659626.1948682 ],
       [ 472973.30432387],
       [ 515274.24253999],
       [ 569537.60718794],
       [ 368160.72332754],
       [ 487945.22137698],
       [ 333940.25637215],
       [ 881178.16468155],
       [ 335402.05474555],
       [ 403764.06798749],
       [ 742481.14209478],
       [ 537789.78004703],
       [ 488197.33363891],
       [ 588449.73943788],
       [ 311255.7157969 ],
       [ 277145.991884  ],
       [ 334560.21637267],
       [ 375619.64610368],
       [ 344660.78203149],
       [ 868342.07750319],
       [1067720.31218341],
       [ 963217.71118734],
       [ 302812.38923176],
       [ 314070.15798528],
       [ 726383.84432061],
       [ 611638.1122496 ],
       [ 708623.53044381],
       [ 562725.47435179],
       [ 537000.81697831],
       [ 578007.37140516],
       [ 481384.80851536],
       [ 604152.75182139],
       [ 698239.42243681],
       [ 287951.21522113],
       [ 895081.37255525],
       [ 483778.13537361],
       [ 491011.77582729],
       [ 684167.2114949 ],
       [ 256992.35114895],
       [ 543050.42439781],
       [ 858946.16952269],
       [ 742902.25742492],
       [ 625736.76084358],
       [ 509671.7958153 ],
       [ 949145.50024543],
       [ 638657.15341235],
       [ 679327.29018687],
       [ 708260.6751394 ],
       [ 436890.97659546],
       [ 686981.65368328],
       [ 582310.04961901],
       [1682136.59298796],
       [ 508856.3950945 ],
       [ 594894.02453545],
       [ 457632.75495739],
       [ 682168.17002732],
       [ 466470.75920059],
       [ 789090.53553371],
       [ 379392.05442899],
       [ 594473.3014927 ],
       [ 731565.56800256],
       [ 637362.76962309],
       [ 701053.86462519],
       [ 687375.93907395],
       [ 518115.12238044],
       [ 318910.07929332],
       [ 608177.27240862],
       [ 803835.58178029],
       [1537416.40063376],
       [ 295158.02573534],
       [ 752923.51012751],
       [ 569642.96550885],
       [ 316095.63710494],
       [ 560331.75520615],
       [ 813631.55216042],
       [ 760946.11364991],
       [ 608513.69006096],
       [ 653771.23586039],
       [ 279171.47100366],
       [ 551014.76789449],
       [ 747152.06033462],
       [ 458339.00111978],
       [ 551745.86322488],
       [ 454874.87468657],
       [ 269039.08297119],
       [ 714141.67177809],
       [1478313.11467777],
       [1157414.22218561],
       [ 585661.73490158],
       [ 534043.8093738 ],
       [ 345081.89736162],
       [ 513106.1980042 ],
       [ 267629.76761456],
       [ 765643.46954182],
       [ 682562.45541799],
       [ 330167.84804685],
       [1389802.84542235],
       [ 691374.02200911],
       [ 243709.10327577],
       [ 354877.47545436],
       [ 704657.26988229],
       [ 271485.28513359],
       [ 237291.25583028],
       [ 507646.31669564],
       [ 375987.88612966],
       [ 533707.39172146],
       [ 516762.47856546],
       [ 328311.37199539],
       [ 670010.69516259],
       [ 732801.6917661 ],
       [ 540630.65988749],
       [ 238532.76431539],
       [ 679327.29018687],
       [ 270444.20980294],
       [ 429883.01075164],
       [ 537646.82234351],
       [ 494757.74650052],
       [ 648646.58374129],
       [ 651182.86830306],
       [ 519524.43773708],
       [ 971687.47540455],
       [ 351894.03019778],
       [ 200308.82970327],
       [ 525743.04822478],
       [ 942306.53746981],
       [ 619013.92583201],
       [ 276693.44646761],
       [ 641503.41797438],
       [ 384062.97266882],
       [ 690947.9142448 ],
       [ 817234.95741752],
       [ 481921.65932216],
       [ 454844.75042108],
       [1162674.86653639],
       [ 399908.55046845],
       [ 904929.82595214],
       [ 425012.85555402],
       [ 287556.53754308],
       [ 234476.8136419 ],
       [ 260595.75640605],
       [ 753964.58545816],
       [ 859451.59024323],
       [ 822074.87872556],
       [ 429909.44840371],
       [ 443645.63784757],
       [ 634574.37279939],
       [ 282774.87626076],
       [ 764096.97349062],
       [ 769246.87479892],
       [ 896828.30176091],
       [ 621912.6695439 ],
       [ 245734.58239542],
       [ 316884.60017367],
       [ 881967.12775028],
       [ 288740.17828986],
       [ 293185.42191984],
       [ 310466.75272818],
       [ 453382.95204769],
       [ 668069.52143334],
       [ 625037.48788683],
       [ 499455.10239243],
       [ 605731.07024623],
       [ 314517.3186801 ],
       [ 541671.73521814],
       [ 938703.13221271],
       [ 505115.80914284],
       [ 521970.63989948],
       [ 713100.59644744],
       [ 498245.02399357],
       [ 267461.15683375],
       [ 277482.40953634],
       [ 518115.12238044],
       [ 570379.44556082],
       [1359659.38207096],
       [ 765786.03495794],
       [ 427966.17654511],
       [ 624947.79777486],
       [1272832.78956129],
       [ 287951.21522113],
       [ 393295.26230269],
       [ 783713.76341888],
       [ 321724.5214817 ],
       [ 313281.19491656],
       [ 316968.90556407],
       [ 251363.46677219],
       [ 654812.71121224],
       [ 410997.31615377],
       [ 679327.29018687],
       [ 387298.13789994],
       [ 231662.37145352],
       [ 399765.98505232],
       [ 275088.6903907 ],
       [ 268250.11990247],
       [ 305006.87141962],
       [ 598892.10747061],
       [ 672345.76199512],
       [ 612821.75299638],
       [ 289187.33898468],
       [ 585913.84716351],
       [ 410208.35308505],
       [1150459.13164593],
       [ 501085.90383403],
       [ 968335.79012199],
       [ 467312.59757346],
       [ 500354.80850364],
       [ 602153.71035381],
       [ 332192.93487911],
       [ 620081.43881474],
       [ 465429.68386993],
       [ 444492.46478773],
       [ 884781.56993866],
       [ 307284.07051382],
       [ 534043.8093738 ],
       [ 528835.64803978],
       [ 824410.33784548],
       [ 734038.20781703],
       [ 507898.42895757],
       [ 276693.44646761],
       [ 704657.26988229],
       [ 727146.36973726],
       [ 604573.47486413],
       [ 968762.29017369],
       [ 483894.65542506],
       [ 388876.45632478],
       [ 453382.95204769],
       [ 318910.07929332],
       [ 298814.3062966 ],
       [1092537.39217428],
       [ 435538.33278047],
       [ 374210.33074704],
       [ 517972.55696431],
       [ 596776.93823897],
       [ 477754.96560618],
       [ 494725.92412687],
       [ 424254.12637487],
       [1121499.30904133],
       [ 425464.20477373],
       [ 699028.38550553],
       [ 571446.95854355],
       [ 770204.84093585],
       [ 525574.04515658],
       [ 291186.38045226],
       [ 256624.11112296],
       [ 438442.46508083],
       [ 639808.57949809],
       [ 803978.14719642],
       [ 707839.95209666],
       [ 866542.27299339],
       [ 513527.31333433],
       [ 347054.50117713],
       [ 494784.1841526 ],
       [ 522759.6029682 ],
       [ 328732.09503813],
       [ 304953.99611547],
       [ 937583.13621322],
       [ 387162.54568946],
       [ 520929.56456882],
       [ 763760.55583829],
       [ 663113.47236125],
       [ 435344.48054427],
       [ 397094.10828007],
       [ 405763.10945507],
       [ 555491.83389811],
       [ 613637.15371718],
       [ 677580.36098121],
       [ 772203.88240343],
       [ 485467.19684093],
       [ 458901.09338196],
       [ 345870.86043035],
       [ 447754.06767092],
       [ 453382.95204769],
       [ 793930.45684175],
       [ 254966.87202929],
       [ 388902.89397686],
       [ 606151.79328897],
       [ 388540.03867245],
       [ 645437.85616225],
       [ 339400.13768071],
       [ 868342.07750319],
       [ 662045.95937852],
       [ 529598.56574382],
       [ 337032.85618715],
       [ 516341.75552271],
       [ 699028.38550553],
       [ 263410.19859443],
       [ 377393.01296141],
       [ 410208.35308505],
       [ 645948.66160436],
       [ 611664.54990168],
       [ 516089.64326078],
       [ 518115.12238044],
       [ 230989.53614885],
       [ 575445.04147871],
       [1458411.59007154],
       [ 388455.34099465],
       [ 363941.15430741],
       [ 544234.06514459],
       [ 389718.29469766],
       [1104980.89593703],
       [ 470916.00283056],
       [1219700.19035596],
       [ 478965.04400504],
       [ 256176.95042815],
       [ 501848.42925068],
       [ 534975.33785865],
       [ 607340.81875732],
       [ 505226.55218532],
       [ 440351.81643643],
       [ 387692.815578  ],
       [ 632970.00900986],
       [ 417020.87820859],
       [ 373620.6046361 ],
       [ 267855.44222441],
       [ 589265.14015868],
       [ 609665.5084341 ],
       [ 677328.24871929],
       [ 407399.29561824],
       [1127943.59413889],
       [ 986548.64941518],
       [ 457238.46956672],
       [ 638598.89338663],
       [ 384348.10350108],
       [ 354035.63708149],
       [ 988495.207866  ],
       [ 374409.56770482],
       [ 739245.97686366],
       [ 427489.68389339],
       [ 445728.58855127],
       [ 539304.45372458],
       [ 359548.39369419],
       [ 873997.39953203],
       [ 963554.12883967],
       [ 248154.34690575],
       [ 442125.18329416],
       [ 472268.64664555],
       [ 260201.07872799],
       [ 507530.18893159],
       [1040391.2910204 ],
       [ 338274.75695965],
       [ 984102.44725278],
       [ 473084.04736635],
       [ 557490.8753657 ],
       [ 276693.44646761],
       [ 419162.4850923 ],
       [ 489970.70049663],
       [ 290765.65740952],
       [ 915398.63163694],
       [1037208.60880604],
       [ 591264.18162626],
       [ 337032.85618715],
       [ 382063.93120124],
       [ 680394.8031696 ],
       [ 900931.74301698],
       [ 453213.94897948],
       [ 774650.08456583],
       [ 619435.04116215],
       [ 496388.54794212],
       [1075795.39872257],
       [ 391638.02320901],
       [ 324538.96367008],
       [ 767247.83333134],
       [ 339400.13768071],
       [ 601195.74421688],
       [ 592079.58234706],
       [ 507898.42895757],
       [1024010.05861065],
       [ 477728.52795411],
       [ 652195.41171919],
       [ 385667.33645834],
       [ 322513.48455043],
       [ 317616.89170074],
       [ 817571.37506986],
       [ 670910.4012738 ],
       [ 204306.91263844],
       [ 384510.13336364],
       [ 480627.2755329 ],
       [ 440377.86180112],
       [ 308073.03358254],
       [ 336585.69549233],
       [1231378.68215223],
       [ 752581.7077536 ],
       [ 865080.47461999],
       [ 245366.34236944],
       [ 704657.26988229],
       [ 402050.15735216],
       [ 209935.7970152 ],
       [ 453382.95204769],
       [ 387666.37792593],
       [ 498414.02706178],
       [ 378434.08829206],
       [ 424280.56402695],
       [ 438326.33731678],
       [ 657484.58798449],
       [ 543897.64749226],
       [ 490707.1805486 ],
       [ 811264.27066685],
       [ 294000.82264064],
       [ 422424.0879755 ],
       [ 661651.67398786],
       [ 378434.08829206],
       [ 538999.85844589],
       [ 649183.82683548],
       [ 476939.56488538],
       [ 486650.83758771],
       [ 514316.27640306],
       [ 559095.23915522],
       [ 974475.47994086],
       [ 758131.67146153],
       [ 392506.29923396],
       [ 496388.54794212],
       [ 215564.68139196],
       [ 741245.01833124],
       [ 579495.60743063],
       [ 378434.08829206],
       [ 720754.95994385],
       [ 670095.000553  ],
       [ 535001.77551073],
       [ 752923.51012751],
       [ 510318.19346789],
       [ 480122.24709975],
       [1234555.97964502],
       [1047346.38156007],
       [ 279507.88865599],
       [ 469454.20445717],
       [ 412207.39455263],
       [ 578007.37140516],
       [ 689290.67515113],
       [ 533228.408653  ],
       [ 561120.71827488],
       [ 221193.56576872],
       [ 432103.53830418],
       [ 661651.67398786],
       [ 466666.19992087],
       [ 602011.14493768],
       [ 452424.98591076],
       [ 423465.16330615],
       [1018770.07490299],
       [ 575192.92921678],
       [ 306979.47523513],
       [ 415390.07676699],
       [ 784192.35419995],
       [ 515921.03247997],
       [ 677664.66637162],
       [ 473730.44501895],
       [ 326958.72818041],
       [ 287162.25215241],
       [ 737641.61307414],
       [ 334218.41399877],
       [ 423663.49833126],
       [ 561372.83053681],
       [ 513132.63565628],
       [ 533254.84630507],
       [ 437679.93966418],
       [ 936593.34770265],
       [ 454171.91511641],
       [ 500612.30548714],
       [1292954.6079227 ],
       [ 773019.28312423],
       [ 291554.62047824],
       [ 794719.41991048],
       [ 544091.49972846],
       [ 704657.26988229],
       [ 401934.02958811],
       [ 237291.25583028],
       [ 815572.33360228],
       [ 516341.75552271],
       [ 614820.79446396],
       [ 260595.75640605],
       [ 267461.15683375],
       [ 690585.05894039],
       [ 660468.03324108],
       [ 351105.06712905],
       [ 485104.34153652],
       [ 969661.9962849 ],
       [ 275904.48339889],
       [ 754580.74922118],
       [ 664860.7938543 ],
       [ 797954.5851416 ],
       [ 831585.71827343],
       [ 419609.64578712],
       [1011878.62911061],
       [ 496388.54794212],
       [ 273879.00427923],
       [1149418.05631528],
       [ 482316.33700022],
       [ 382063.93120124],
       [ 644622.45544145],
       [ 849682.05751518],
       [ 369622.52170093],
       [ 484567.49072973],
       [ 377197.57224113],
       [ 845347.55692768],
       [ 502017.43231888],
       [ 428699.37000485],
       [1220004.78563465],
       [ 811489.94527671],
       [ 795534.82063128],
       [ 524532.96982593],
       [ 704541.14211824],
       [ 377393.01296141],
       [1270439.07041565],
       [ 905155.50056199],
       [ 668069.52143334],
       [ 318910.07929332],
       [ 774229.36152309],
       [ 548595.00338417],
       [ 669616.01748454],
       [ 915624.30624679],
       [ 532413.0079322 ],
       [ 328732.09503813],
       [ 471618.56237954],
       [ 626525.7239123 ],
       [ 218379.12358034],
       [ 642739.54173792],
       [ 882414.2884451 ],
       [ 375619.64610368],
       [ 749661.90724431],
       [1181928.80116023],
       [ 259806.79333733],
       [ 327353.40585846],
       [ 377024.77293542],
       [ 262173.6825435 ],
       [ 371989.8031945 ],
       [ 486203.6768929 ],
       [ 203517.94956971],
       [ 345476.18275229],
       [ 561457.13592721],
       [ 502690.26762355],
       [ 656022.7896111 ],
       [ 502269.54458081],
       [ 503532.10599643],
       [ 362026.41823024],
       [ 523575.003689  ],
       [ 952185.61704367],
       [ 465681.79613186],
       [ 452424.98591076],
       [ 426647.84552051],
       [ 548931.4210365 ],
       [ 372384.48087256],
       [ 478543.92867491],
       [ 288371.93826388],
       [ 408351.87703359],
       [ 425911.36546855],
       [ 566633.47488759],
       [ 822863.84179428],

In [ ]:
y_pred=model.predict(x_test)

In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [ ]:
mean_absolute_error(y_test,y_pred)

206655.53056815045

In [ ]:
mean_squared_error(y_test,y_pred)

827962253230.9869

In [ ]:
r2_score(y_test,y_pred)

0.0689201600521615

In [ ]:
import joblib

In [ ]:
joblib.dump(model,"multiple.pkl")

['multiple.pkl']

In [ ]:
df_bronze.write \
  .mode('overwrite') \
  .parquet('sales_bronze.parquet')

print("Bronze Parquet saved : sales_bronze.parquet")

import os

def get_dir_size(path):
  if os.path.isfile(path):
    return os.path.getsize(path)/1024
  total=0
  for dirpath, dirnames, filenames in os.walk(path):
    for f in filenames:
      fp=os.path.join(dirpath, f)
      total+=os.path.getsize(fp)/1024
  return total

Bronze Parquet saved : sales_bronze.parquet

In [ ]:

df_silver=df_bronze \
  .dropDuplicates() \
  .dropna(subset=['order_id','product','revenue'])

df_silver=df_silver.withColumn(
      'order_date',
      to_date(col('order_date'),'yyyy-MM-dd')
)

df_silver=df_silver \
    .withColumn('order_year',year(col('order_date'))) \
    .withColumn('order_month',month(col('order_date')))



df_silver=df_silver.withColumn(
    'revenue_category',
    F.when(col('revenue')>40000,'High')
    .when(col('revenue')>10000,'Medium')
    .otherwise('Low')
)

print(f"Silver layer rows : {df_silver.count()}")
print('New columns added: order_year, order_month, revenue_category')
df_silver.select('product','revenue','order_year','order_month','revenue_category').show(10)

Silver layer rows : 5000
New columns added: order_year, order_month, revenue_category
+----------+-------+----------+-----------+----------------+
|   product|revenue|order_year|order_month|revenue_category|
+----------+-------+----------+-----------+----------------+
|  Keyboard|  13200|      2023|          2|          Medium|
|    Webcam|  17500|      2023|          1|          Medium|
|   Speaker|  58500|      2023|          4|            High|
|  Keyboard|   9600|      2023|         12|             Low|
|    Laptop| 180000|      2023|          8|            High|
|Headphones|  38500|      2023|          5|          Medium|
|    Webcam|  35000|      2023|         11|          Medium|
|    Laptop| 360000|      2023|          1|            High|
|    Tablet| 320000|      2023|          6|            High|
|    Laptop| 225000|      2023|          6|            High|
+----------+-------+----------+-----------+----------------+
only showing top 10 rows

In [ ]:
import os
df_silver.write \
  .mode('overwrite') \
  .parquet('sales_silver.parquet')

print("Silver Parquet saved : sales_silver.parquet")
print(f"Silver size : {get_dir_size("sales_silver.parquet")} KB")

df_verify=spark.read.parquet('sales_silver.parquet')
print(f"Read-back rows : {df_verify.count()} (should match silver count)")
df_verify.printSchema()

Silver Parquet saved : sales_silver.parquet
Silver size : 59.814453125 KB
Read-back rows : 5000 (should match silver count)
root
 |-- order_id: integer (nullable = true)
 |-- customer_name: string (nullable = true)
 |-- product: string (nullable = true)
 |-- category: string (nullable = true)
 |-- quantity: integer (nullable = true)
 |-- unit_price: integer (nullable = true)
 |-- revenue: integer (nullable = true)
 |-- order_date: date (nullable = true)
 |-- city: string (nullable = true)
 |-- region: string (nullable = true)
 |-- sales_rep: string (nullable = true)
 |-- payment_method: string (nullable = true)
 |-- order_status: string (nullable = true)
 |-- order_year: integer (nullable = true)
 |-- order_month: integer (nullable = true)
 |-- revenue_category: string (nullable = true)

In [ ]:
top_products = df_silver \
  .groupBy('product') \
  .agg(
      F.sum('revenue').alias('total_revenue'),
      F.count('order_id').alias('num_orders'),
      F.avg('revenue').alias('avg_order_revenue')
  ) \
  .orderBy('total_revenue' , ascending=False) \
  .limit(5)
top_products.show()

+-------+-------------+----------+------------------+
|product|total_revenue|num_orders| avg_order_revenue|
+-------+-------------+----------+------------------+
| Laptop|    182700000|       502|363944.22310756973|
| Tablet|    135104000|       532| 253954.8872180451|
|Monitor|     82126000|       481|170740.12474012474|
|Printer|     44544000|       488| 91278.68852459016|
|Speaker|     16317000|       470| 34717.02127659575|
+-------+-------------+----------+------------------+

In [ ]:
from pyspark.sql import functions as F

revenue_by_region = df_silver \
    .groupBy('region') \
    .agg(
        F.sum('revenue').alias('total_revenue'),
        F.count('order_id').alias('num_orders'),
        F.avg('revenue').alias('avg_order_revenue')
    ) \
    .orderBy('total_revenue', ascending=False)

revenue_by_region.show(truncate = False)

In [ ]:
print(' === Payment Method sucessfully')

In [ ]:
# Gold Table 1: Revenue by region

gold_region = region_revenue
revenue_by_region.write.mode("overwrite").parquet("gold/revenue_by_region")
print("Gold ! saved: gold_region_revenue.parquet")

#Gold Table 2: Product performance summary

gold_products = df_silver \

In [ ]:

revenue_pd = spark.read.parquet("gold_region_revenue.parquet").toPandas()

product_pd = spark.read.parquet("gold_product_summary").toPandas()

monthly_pd = spark.read.parquet("gold_monthly_trend.paruqet").toPandas()


print("Gold tables converted to Pandas:")
print(f"   Region: {region_pd.shape}")
print(f"   Product: {product_pd.shape}")
print(f"   Monthly: {monthly_pd.shape}")

region_pd = region_pd.sort_values('total_revenue',ascendin=False)
product_pd = product_pd.sort_values('total_revenue',ascending=False)
monthly_pd = monthly_pd.sort_values('order_moth')

In [ ]:
fig, axes = plt.subplots(2,2, figsize =(18,13))
fig.suptitle(
    'Big Data Sales Dashboard - PySpark'
)

# panel 1: revenue by region

ax1 = axes[0][0]
bars1 = ax1.bar(region_pd['region'],region_pd['total_revenue'], color = colors4[len(region_pd)],wedgecolor='white')
for bar in bar1:
  ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height()*1.01, f'(bar.gey_height()/le6:.1f)"

ax2= axe[0][1]
top5_prod = product_pd.head(S).sort_values('total_revenue',ascending=False)
bars2 = ax2.barh(top5_prod['product'],top5_prod['total_revenue'],color='#4FC3F7', edgecolor= 'white')

for bar in bars2:
      ax2.text(bar.get_width()*1.01, bar.get_y()+ bar.get_height()/2,
               f'$(bar.get_width()/1e6: .2f)M', va='center',fontsize=0, fontweight='bold',color='#1E2761')

ax2.set_title("Top 5 branches by Revenue", fontsize='0',fontweight='bold')
ax2.set_xlabel('Total Revenue($)')
ax1.set_ylabel('Total Revenue($)')

In [ ]:
# Activity 2: CSV to Parquet Corporation

print("=== Activity 2: File Format Comparison ===")
print()

csv_kb = get_dir_size("large_sales_data.csv")
bronze_db =get_dir_size('sales_bronze.parquet')
silver_db = get_dir_size('sales_silver.parquet')
gold_db = get_dir_size('gold_region_revenue.parquet') + get_dir_size('gold_product_summary.parquet') + get_dir_size('gold_monthly_trend.parquet'))
print(f"{'File':<38}, {'Size(KB)}' :>10},{'vs CSV' :>10}")